FROM golang:1.26-alpine

RUN apk add --no-cache bash git nodejs npm \
    && npm install --global typescript \
    && ln -s /usr/local/go/bin/go /usr/local/bin/go \
    && ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt

ENV HOME=/tmp/.home \
    GOCACHE=/tmp/go-build \
    GOMODCACHE=/tmp/go-mod \
    GOTMPDIR=/tmp \
    TMPDIR=/tmp \
    npm_config_cache=/tmp/npm-cache

WORKDIR /workspace